trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscription: Visual Studio Professional Subscription(d27e7e46-ee4b-4636-a893-80884653852d)
  resourceGroup: AksTerraform-RG
  storageAccount: jayaaksterraform
  container: tfstate
  tfstateFile: terraform-dev.tfstate
  anyTfChanges: false

steps:

- task: TerraformInstaller@0
  displayName: install Terraform v1.1.1
  inputs:
    terraformVersion: '1.1.1'

- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
  displayName: terraform init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/az-vm'
    backendType: azurerm
    backendAzureRmResourceGroupName: 'AksTerraform-RG'
    backendAzureRmStorageAccountName: 'jayaaksterraform'
    backendAzureRmContainerName: 'tfstate'
    backendAzureRmKey: 'terraform-dev.tfstate'
    environmentServiceNameAzureRM: 'AKSTerraform'

- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
  displayName: terraform plan -out=tfplan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/az-vm'
    commandOptions: '-out=tfplan'
    # commandOptions: '-detailed-exitcode -out=tfplan'
    environmentServiceNameAzureRM: 'AKSTerraform'

- task: PowerShell@2
  displayName: detect any terraform change
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/az-vm'
    targetType: 'inline'
    script: |
      # Write-Host "LASTEXITCODE : $LASTEXITCODE"
      $plan = $(terraform show -json tfplan | ConvertFrom-Json)
      $actions = $plan.resource_changes.change.actions
      Write-Host "Terraform actions : $actions"
      if (($actions -contains 'create') -or ($actions -contains 'delete') -or ($actions -contains 'update'))
      {
        Write-Host "Terraform will perform the following actions : $actions"
        Write-Host "##vso[task.setvariable variable=anyTfChanges;]true"
      }
      else
      {
        Write-Host "There is no change detected in Terraform tfplan file"
      }
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-cli.TerraformCLI@0
  displayName: terraform apply tfplan
  condition: eq(variables.anyTfChanges, true)
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/az-vm'
    commandOptions: 'tfplan'
    environmentServiceNameAzureRM: 'AKSTerraform'
